# Generated by Django 4.2.5 on 2023-09-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
