# Generated by Django 4.2.5 on 2023-09-22 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcsapi', '0002_notification_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='name',
        ),
    ]
