# Generated by Django 4.2.5 on 2023-09-26 09:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcsapi', '0003_remove_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='account_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='member_source_identifier',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gcsapi.membersourceidentifier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='do_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pu_address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trip_date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='trip_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_body',
            field=models.TextField(),
        ),
    ]
