# Generated by Django 4.2.5 on 2023-09-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcsapi', '0004_notification_account_id_notification_last_modified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='member_source_identifier',
        ),
    ]
