# Generated by Django 4.2.5 on 2023-09-26 10:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gcsapi', '0005_remove_notification_member_source_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='member_source_identifier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcsapi.membersourceidentifier'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BrokerClientTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deactivation_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('broker_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcsapi.brokerclient')),
                ('notification_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcsapi.notificationtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='brokerclient',
            name='notification_template',
            field=models.ManyToManyField(related_name='broker_client', related_query_name='broker_clients', through='gcsapi.BrokerClientTemplate', to='gcsapi.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='broker_client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gcsapi.brokerclient'),
            preserve_default=False,
        ),
    ]
